### ISSUE TITLE
Improve code quality by importing express and ejs module

### ISSUE THREAD

**Issue by Divyanshgarg-04** [Animesh606/WeatherForcasting#10] opened 2024-01-14 20:27 UTC
Whole backend code is written using http createServer i can upgrade it to express.

Please assign this to me under JWOC'24

**Comment by Animesh606** [comment] 2024-01-14 20:46
@Divyanshgarg-04 It is a great issue. Add EJS and express to the project. You are assigned this issue

**Closed as completed** 2024-01-15 12:21 UTC
Labels: JWOC, Medium

**Comment by Animesh606** [comment] 2024-01-15 12:23
The issue is resolved by @Divyanshgarg-04 with pull request #12
